### ISSUE TITLE
Question: Why rotation bucket in Bloom filters? Is there a plan to introduce sliding buckets so as to manage retention of keys?

### ISSUE THREAD

**Issue by rnbokade** [krakendio/bloomfilter#19]
I mean this would actually make sense....
For example if my access token is valid only for 3 days, it doesn't make any sense to keep having it in the filter for more than 3 days since anyway it is going to expire after that time.

**Comment by alombarte** [comment]
Hi @rnbokade ,

Apologies, but I don't understand your question. If I can improve the documentation I will.

An entry lives in the bloomfilter twice the bloomfilter TTL.

**Comment by rnbokade** [comment]
Thanks and sorry. I didn't see that documentation.  It is indeed well documented
